version: '3.8'
services:
  auth-db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Auth
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-qm
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025