spring:
  application:

    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  config:
    import: optional:configserver:http://localhost:8888
  servlet:
    multipart:
      max-file-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: nabil
    password: nabil
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8100
  servlet:
    context-path: /api/v1/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
springdoc:
  default-consumes-media-type: application/json
application:
  security:
    jwt:
      secret-key: Ab6kWuS1t5G4qxTlB66JpPixALHGY0gP
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:3000/activate-acount
